config/routes.rb
Rainforest::Application.routes.draw do
  # get    'products'          => 'products#index'
  # post   'products'          => 'products#create'
  # get    'products/new'      => 'products#new'
  # get    'products/:id/edit' => 'products#edit'
  # get    'products/:id'      => 'products#show',
  # put    'products/:id'      => 'products#update'
  # delete 'products/:id'      => 'products#destroy'
  resources :products
  root      :to                => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents
  
  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => { :only_integer => true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  	
  	respond_to do |format|
  		format.html
  		format.json { render json: @products }
  	end
  end

  def show
  	@product = Product.find(params[:id])
  	
  	respond_to do |format|
	  	format.html
	  	format.json { render json: @product }
	  end	
  end

  def new
  	@product = Product.new

  	respond_to do |format|
  		format.html
  		format.json { render json: @product }
  	end 
  end

  def create
  	@product = Product.new(params[:product])

    respond_to do |format|
    	if @product.save
    		format.html { redirect_to product_path(@product), notice: 'Product was successfully created.' }
        format.json { render json: product_path(@product), status: :created, location: @product }
    	else
    		format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity}
    	end
    end
  end

  def edit
  	@product = Product.find(params[:id])

  	respond_to do |format|
  		format.html
  		format.json { render json: @product }
  	end
  end

  def update
  	@product = Product.find(params[:id])

    respond_to do |format|
    	if @product.update_attributes(params[:product])
    		format.html { redirect_to product_path(@product), notice: 'Product was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
    		render :edit
    	end
    end
  end

	def destory
	  @product = Product.find(params[:id])
	  @product.destory

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content}
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

	<% if @product.errors.any? %>
		<div id = "error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
				<% @product.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class = 'field'>
		<%= f.label :name, "Product Name" %><br />
		<%= f.text_field :name %>
	</div>
	<div class = 'field'>
		<%= f.label :description, "Description" %><br />
		<%= f.text_area :description %>
	</div>
	<div class = 'field'>
		<%= f.label :price_in_cents, "Price in cents" %><br />
		<%= f.text_field :price_in_cents %>
	</div>
	<div class = 'actions'>
		<%= f.submit "Save Product" %>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit the product</h1>
<%= render 'form' %>
<div class = 'back'>
	<p><%= link_to 'Back to the index', products_path %> | <%= link_to 'Back to the product', product_path %> </p>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<p><%= link_to "Add a new product", new_product_path %>
	
<div class = 'index_products'>
	<% @products.each do |p| %>
		<h3><%= link_to p.name, product_path(p) %></h3>
		<h4><%= number_to_currency(p.price_in_cents/100) %></h4>
		<p><%= truncate(p.description, :length => 50) %></p>
	<% end %>
</div>

app/views/products/new.html.erb
<h1>Add a new product</h1>
<%= render 'form' %>
<div class = 'back'>
	<p><%= link_to 'Back to all products', products_path %></p>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>Price: <%= number_to_currency(@product.price_in_cents / 100)%></h3>
<div class = 'product_description'>
	<p> <%= @product.description %> </p>
</div>